// Codopia Platform Database Types
// Generated by Agent Athena (Database Architect)
// Date: September 16, 2025

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type UserRole = 'parent' | 'teacher' | 'admin' | 'child'
export type TierType = 'magic_workshop' | 'innovation_lab' | 'professional_studio'
export type SubscriptionStatus = 'active' | 'inactive' | 'cancelled' | 'past_due'
export type ProjectStatus = 'draft' | 'in_progress' | 'completed' | 'shared'
export type LessonType = 'interactive' | 'video' | 'reading' | 'project' | 'assessment'

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          role: UserRole
          phone: string | null
          timezone: string
          language: string
          onboarding_completed: boolean
          marketing_consent: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          role?: UserRole
          phone?: string | null
          timezone?: string
          language?: string
          onboarding_completed?: boolean
          marketing_consent?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          role?: UserRole
          phone?: string | null
          timezone?: string
          language?: string
          onboarding_completed?: boolean
          marketing_consent?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      children: {
        Row: {
          id: string
          parent_id: string
          name: string
          age: number
          tier: TierType
          avatar_url: string | null
          bio: string | null
          interests: string[] | null
          learning_goals: string[] | null
          accessibility_needs: string[] | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          parent_id: string
          name: string
          age: number
          tier?: TierType
          avatar_url?: string | null
          bio?: string | null
          interests?: string[] | null
          learning_goals?: string[] | null
          accessibility_needs?: string[] | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          parent_id?: string
          name?: string
          age?: number
          tier?: TierType
          avatar_url?: string | null
          bio?: string | null
          interests?: string[] | null
          learning_goals?: string[] | null
          accessibility_needs?: string[] | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      subscription_plans: {
        Row: {
          id: string
          name: string
          description: string | null
          price_monthly: number | null
          price_yearly: number | null
          features: Json | null
          max_children: number | null
          tier_access: TierType[] | null
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          price_monthly?: number | null
          price_yearly?: number | null
          features?: Json | null
          max_children?: number | null
          tier_access?: TierType[] | null
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          price_monthly?: number | null
          price_yearly?: number | null
          features?: Json | null
          max_children?: number | null
          tier_access?: TierType[] | null
          is_active?: boolean
          created_at?: string
        }
      }
      subscriptions: {
        Row: {
          id: string
          user_id: string
          plan_id: string
          status: SubscriptionStatus
          stripe_subscription_id: string | null
          stripe_customer_id: string | null
          current_period_start: string | null
          current_period_end: string | null
          trial_end: string | null
          cancelled_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          plan_id: string
          status?: SubscriptionStatus
          stripe_subscription_id?: string | null
          stripe_customer_id?: string | null
          current_period_start?: string | null
          current_period_end?: string | null
          trial_end?: string | null
          cancelled_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          plan_id?: string
          status?: SubscriptionStatus
          stripe_subscription_id?: string | null
          stripe_customer_id?: string | null
          current_period_start?: string | null
          current_period_end?: string | null
          trial_end?: string | null
          cancelled_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      modules: {
        Row: {
          id: string
          tier: TierType
          name: string
          description: string | null
          order_index: number
          estimated_duration_hours: number | null
          learning_objectives: string[] | null
          prerequisites: string[] | null
          cover_image_url: string | null
          is_published: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tier: TierType
          name: string
          description?: string | null
          order_index: number
          estimated_duration_hours?: number | null
          learning_objectives?: string[] | null
          prerequisites?: string[] | null
          cover_image_url?: string | null
          is_published?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tier?: TierType
          name?: string
          description?: string | null
          order_index?: number
          estimated_duration_hours?: number | null
          learning_objectives?: string[] | null
          prerequisites?: string[] | null
          cover_image_url?: string | null
          is_published?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      lessons: {
        Row: {
          id: string
          module_id: string
          name: string
          description: string | null
          type: LessonType
          order_index: number
          content: Json | null
          estimated_duration_minutes: number | null
          difficulty_level: number | null
          learning_objectives: string[] | null
          resources: Json | null
          is_published: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          module_id: string
          name: string
          description?: string | null
          type: LessonType
          order_index: number
          content?: Json | null
          estimated_duration_minutes?: number | null
          difficulty_level?: number | null
          learning_objectives?: string[] | null
          resources?: Json | null
          is_published?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          module_id?: string
          name?: string
          description?: string | null
          type?: LessonType
          order_index?: number
          content?: Json | null
          estimated_duration_minutes?: number | null
          difficulty_level?: number | null
          learning_objectives?: string[] | null
          resources?: Json | null
          is_published?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      exercises: {
        Row: {
          id: string
          lesson_id: string
          name: string
          description: string | null
          instructions: Json | null
          starter_code: string | null
          solution_code: string | null
          test_cases: Json | null
          hints: Json | null
          difficulty_level: number | null
          estimated_time_minutes: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          lesson_id: string
          name: string
          description?: string | null
          instructions?: Json | null
          starter_code?: string | null
          solution_code?: string | null
          test_cases?: Json | null
          hints?: Json | null
          difficulty_level?: number | null
          estimated_time_minutes?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          lesson_id?: string
          name?: string
          description?: string | null
          instructions?: Json | null
          starter_code?: string | null
          solution_code?: string | null
          test_cases?: Json | null
          hints?: Json | null
          difficulty_level?: number | null
          estimated_time_minutes?: number | null
          created_at?: string
          updated_at?: string
        }
      }
      module_progress: {
        Row: {
          id: string
          child_id: string
          module_id: string
          status: ProjectStatus
          progress_percentage: number
          started_at: string
          completed_at: string | null
          last_accessed_at: string
          time_spent_minutes: number
        }
        Insert: {
          id?: string
          child_id: string
          module_id: string
          status?: ProjectStatus
          progress_percentage?: number
          started_at?: string
          completed_at?: string | null
          last_accessed_at?: string
          time_spent_minutes?: number
        }
        Update: {
          id?: string
          child_id?: string
          module_id?: string
          status?: ProjectStatus
          progress_percentage?: number
          started_at?: string
          completed_at?: string | null
          last_accessed_at?: string
          time_spent_minutes?: number
        }
      }
      lesson_progress: {
        Row: {
          id: string
          child_id: string
          lesson_id: string
          status: ProjectStatus
          progress_percentage: number
          started_at: string
          completed_at: string | null
          last_accessed_at: string
          time_spent_minutes: number
          notes: string | null
        }
        Insert: {
          id?: string
          child_id: string
          lesson_id: string
          status?: ProjectStatus
          progress_percentage?: number
          started_at?: string
          completed_at?: string | null
          last_accessed_at?: string
          time_spent_minutes?: number
          notes?: string | null
        }
        Update: {
          id?: string
          child_id?: string
          lesson_id?: string
          status?: ProjectStatus
          progress_percentage?: number
          started_at?: string
          completed_at?: string | null
          last_accessed_at?: string
          time_spent_minutes?: number
          notes?: string | null
        }
      }
      exercise_submissions: {
        Row: {
          id: string
          child_id: string
          exercise_id: string
          code: string
          is_correct: boolean
          test_results: Json | null
          hints_used: number
          attempts: number
          time_spent_minutes: number
          submitted_at: string
        }
        Insert: {
          id?: string
          child_id: string
          exercise_id: string
          code: string
          is_correct?: boolean
          test_results?: Json | null
          hints_used?: number
          attempts?: number
          time_spent_minutes?: number
          submitted_at?: string
        }
        Update: {
          id?: string
          child_id?: string
          exercise_id?: string
          code?: string
          is_correct?: boolean
          test_results?: Json | null
          hints_used?: number
          attempts?: number
          time_spent_minutes?: number
          submitted_at?: string
        }
      }
      projects: {
        Row: {
          id: string
          child_id: string
          name: string
          description: string | null
          type: string | null
          status: ProjectStatus
          code: string | null
          assets: Json | null
          preview_url: string | null
          share_url: string | null
          is_featured: boolean
          is_public: boolean
          likes_count: number
          views_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          child_id: string
          name: string
          description?: string | null
          type?: string | null
          status?: ProjectStatus
          code?: string | null
          assets?: Json | null
          preview_url?: string | null
          share_url?: string | null
          is_featured?: boolean
          is_public?: boolean
          likes_count?: number
          views_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          child_id?: string
          name?: string
          description?: string | null
          type?: string | null
          status?: ProjectStatus
          code?: string | null
          assets?: Json | null
          preview_url?: string | null
          share_url?: string | null
          is_featured?: boolean
          is_public?: boolean
          likes_count?: number
          views_count?: number
          created_at?: string
          updated_at?: string
        }
      }
      project_collaborators: {
        Row: {
          id: string
          project_id: string
          child_id: string
          role: string
          invited_at: string
          joined_at: string | null
        }
        Insert: {
          id?: string
          project_id: string
          child_id: string
          role?: string
          invited_at?: string
          joined_at?: string | null
        }
        Update: {
          id?: string
          project_id?: string
          child_id?: string
          role?: string
          invited_at?: string
          joined_at?: string | null
        }
      }
      messages: {
        Row: {
          id: string
          sender_id: string
          recipient_id: string
          subject: string | null
          content: string
          is_read: boolean
          parent_message_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          sender_id: string
          recipient_id: string
          subject?: string | null
          content: string
          is_read?: boolean
          parent_message_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          sender_id?: string
          recipient_id?: string
          subject?: string | null
          content?: string
          is_read?: boolean
          parent_message_id?: string | null
          created_at?: string
        }
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: string
          title: string
          content: string | null
          data: Json | null
          is_read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          title: string
          content?: string | null
          data?: Json | null
          is_read?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: string
          title?: string
          content?: string | null
          data?: Json | null
          is_read?: boolean
          created_at?: string
        }
      }
      achievements: {
        Row: {
          id: string
          name: string
          description: string | null
          icon_url: string | null
          tier: TierType | null
          category: string | null
          points: number
          requirements: Json | null
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          icon_url?: string | null
          tier?: TierType | null
          category?: string | null
          points?: number
          requirements?: Json | null
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          icon_url?: string | null
          tier?: TierType | null
          category?: string | null
          points?: number
          requirements?: Json | null
          is_active?: boolean
          created_at?: string
        }
      }
      user_achievements: {
        Row: {
          id: string
          child_id: string
          achievement_id: string
          earned_at: string
        }
        Insert: {
          id?: string
          child_id: string
          achievement_id: string
          earned_at?: string
        }
        Update: {
          id?: string
          child_id?: string
          achievement_id?: string
          earned_at?: string
        }
      }
      analytics_events: {
        Row: {
          id: string
          user_id: string | null
          child_id: string | null
          event_type: string
          event_data: Json | null
          session_id: string | null
          ip_address: string | null
          user_agent: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          child_id?: string | null
          event_type: string
          event_data?: Json | null
          session_id?: string | null
          ip_address?: string | null
          user_agent?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string | null
          child_id?: string | null
          event_type?: string
          event_data?: Json | null
          session_id?: string | null
          ip_address?: string | null
          user_agent?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      calculate_module_progress: {
        Args: {
          child_uuid: string
          module_uuid: string
        }
        Returns: number
      }
      create_notification: {
        Args: {
          user_uuid: string
          notification_type: string
          notification_title: string
          notification_content?: string
          notification_data?: Json
        }
        Returns: string
      }
    }
    Enums: {
      user_role: UserRole
      tier_type: TierType
      subscription_status: SubscriptionStatus
      project_status: ProjectStatus
      lesson_type: LessonType
    }
  }
}

